### ISSUE TITLE
Is there support for using dogstatsd?

### ISSUE THREAD

**Issue by jongillies** [DataDog/ansible-datadog#110]
I don't see an option to add the these to the datadog.yml file if you are using dogstatsd:

```
use_dogstatsd: yes
dogstatsd_port: 8125
```

Or am I missing something?

Thanks,
Jon.

**Comment by bradlangel** [comment]
Those are the defaults so you don't need to set them. And if you want to change the defaults you use the `datadog_config` variable like so:
```
datadog_config:
  dogstatsd_port: xxxx
```

This is because the datadog.conf.j2 template has this chunk of code: 
```
{# These variables are free-style, passed through a hash -#}
{% if datadog_config -%}
{% for key, value in datadog_config.items() -%}
{{ key }}: {{ value }}
{% endfor -%}
{% endif %}
```

And from the README: 
```
datadog_config - Settings to place in the /etc/dd-agent/datadog.conf INI file that go under the [Main] section.
```

See example playbook for more information: https://github.com/DataDog/ansible-datadog#example-playbooks

**Comment by hush-hush** [comment]
Thanks to @bradlangel for the answer: it's the correct one.

The `datadog_config` works the same for agent6 (and the variables are the same for dogstatsd).
I'll update the README to clarify that point.
