### ISSUE TITLE
Datadog version error

### ISSUE THREAD

**Issue by nicgirault** [DataDog/ansible-datadog#137]
Thanks for this repo.

I think each time I provision my server I get an error with this role due to the datadog agent version. It would be great to get something a bit more stable...

Today, using the role with

```
datadog_agent_version: "1:6.0.0-1"
```

gives: `"E: Version '1:6.0.0-1' for 'datadog-agent' was not found"`.

I'm just following what is in the README...

**Comment by hush-hush** [comment]
hi @nicgirault,

Thank you for opening this issue. I just try the role with the agent version you specified and it worked on a debian.

Could you tell me which OS are you using. Also which version of the role you are running ?
The agent version 6 is installed by default since version `2.0.0` of this role..

Thanks

**Comment by hush-hush** [comment]
Hi @nicgirault,

Did you add time to look into this ?

**Comment by hush-hush** [comment]
Closing this issue for now, feel free to reopen if needed.
