### ISSUE TITLE
Install DataDog agent but do not start

### ISSUE THREAD

**Issue by arpansolanki** [DataDog/ansible-datadog#178]
We are trying to create a role using ansible-datadog role. We want to have the agent installed but not started. While doing so we have this in our tasks
  service:
    name: datadog-agent
    state: stopped
    enabled: false

But it is failing Idempotence test in molecule. How do we have agent installed but not running and pass idempotence test in molecule?

**Comment by dabcoder** [comment]
Sorry about the delay in responding.

> But it is failing Idempotence test in molecule. How do we have agent installed but not running and pass idempotence test in molecule?

Do you have a bit more details to share about your molecule setup and the error(s) you are getting?

**Comment by dabcoder** [comment]
I'm not getting any failures when running the idempotence test with molecule. If I set `datadog_enabled` to `false` in a playbook and then have the below in a task:

```
- name: Ensure datadog-agent is not running
  service:
    name: datadog-agent
    state: stopped
    enabled: no
```
 
==> `molecule idempotence` passes. I ran this with molecule `version 2.20.1` with a Ubuntu 18.04 docker image. 
I'm going to close this for now but feel free to reopen this if you have additional details to share such as OS version, molecule version so that we can have a look.
