### ISSUE TITLE
Invalid documentation for datadog_additional_groups

### ISSUE THREAD

**Issue by brmzkw** [DataDog/ansible-datadog#256]
According to [README](https://github.com/DataDog/ansible-datadog#role-variables), `datadog_additional_groups` is a "Comma separated list of additional groups for the datadog_user." but `with_items` is used in [agent-linux.yml](https://github.com/DataDog/ansible-datadog/blob/c53161791aeb9b51a9d6243146f7c4a97f6ef6f7/tasks/agent-linux.yml#L7) so it is actually expected to be a list.

Documentation should be updated.

**Comment by KSerrania** [comment]
Hello @brmzkw,

Thanks for the report! I think the problem lies in the fact that the `with_items` is useless here, as the task is not using `item` but `datadog_additional_groups` directly.
The documentation for the [user module](https://docs.ansible.com/ansible/latest/modules/user_module.html) does state that the `groups` parameter takes a list which can be a comma-separated string (or must be one, if using Ansible 2.2 or lower).
 
Here, we can either:
- remove the unused `with_items` and add to the doc that `datadog_additional_groups` can also be a regular list (if using Ansible 2.3+),
- use `with_items`, and switch `datadog_additional_groups` to a list (but this will be a breaking change as comma-separated lists won't work anymore).

I'd go for solution 1 for now as it's non-breaking.

**Comment by brmzkw** [comment]
Oops, I misunderstood the issue, solution 1 seems good indeed!
