### ISSUE TITLE
Ubuntu 20.04, Ansible 2.10: "couldn't resolve module/action 'win_service'"

### ISSUE THREAD

**Issue by mago0** [DataDog/ansible-datadog#289]
The datadog role works fine with Ansible v2.9 but Ubuntu 20.04 requires Ansible v2.10 due to a bugfix.

```
ERROR! couldn't resolve module/action 'win_service'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/mattw/.ansible/roles/datadog.datadog/handlers/main.yml': line 9, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: restart datadog-agent-win
  ^ here
```

**Comment by albertvaka** [comment]
Given this is an Ansible 2.9 problem on Ubuntu, is there something we can do on our end (apart from recommending to upgrade)?

**Comment by mago0** [comment]
@albertvaka This is a problem with this playbook when using Ansible 2.10 (the latest stable). It worked when I was using 2.9 but I have to use the latest version.

I was able to get a successful run by commenting out this section of code: https://github.com/DataDog/ansible-datadog/blob/master/handlers/main.yml#L9-L14. I'd like to keep using galaxy but I'll have to commit my hacked playbook to our repo until this can be fixed at the source.

**Comment by albertvaka** [comment]
Got it, it's in 2.10 that's broken, sorry for the confusion! 

It seems that in 2.10 many built-in modules have been moved to Ansible Galaxy [1]. That seems to be the case for `win_service`, which is now in the `windows` module [2]. The solution is probably to declare an explicit dependency on `windows` from our role. We will give this a look 👍 

[1] "In preparation for the release of 2.10, many plugins and modules have migrated to Collections on Ansible Galaxy." https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.10.html

[2] https://galaxy.ansible.com/ansible/windows

**Comment by derekwbrown** [comment]
It seems that 2.10 is still in alpha, and is a moving target.
I was able to get a different error with ansible `2.10 alpha 9`:
`TASK [ansible-datadog : Ensure datadog-agent is running] **************************************************************************************************
fatal: [ansible-210]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (win_service) module: enabled. Supported parameters include: failure_command, description, update_password, failure_reboot_msg, force_dependent_services, username, display_name, path, start_mode, failure_actions, desktop_interact, load_order_group, required_privileges, name, password, failure_actions_on_non_crash_failure, service_type, pre_shutdown_timeout_ms, sid_info, dependency_action, error_control, state, failure_reset_period_sec, dependencies, pre_shutdown_timeout, failure_reset_period"}`

We can release a new version of ansible with the fix (the fix is pretty straightforward), but there's no guarantee that it will remain fixed while 2.10 is under development.

The current estimate for beta (which also equals feature freeze) is Sept 01 at which point we can take another pass

**Comment by derekwbrown** [comment]
Created this PR which you're welcome to test with Ansible 2.10alpha9
https://github.com/DataDog/ansible-datadog/pull/294 @mago0

**Comment by derekwbrown** [comment]
Closing this issue for now.
New release 4.4.0 fixes problem with windows & ansible 2.10

**Comment by rowie** [comment]
ERROR! couldn't resolve module/action 'fortios_system_config_backup_restore'. This often indicates a misspelling, missing collection, or incorrect module path.

**Comment by caot** [comment]
centos 7/rhel 7

faied the same with ansible 2.9.9

**Comment by albertvaka** [comment]
@caot The recommended solution is to upgrade to 2.10.

**Comment by nicon89** [comment]
Same issue on 2.11 :(
```
root@279b7abe7c98:/app# ansible-playbook datadog-docker.yml -t syncconfd
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or
trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
[WARNING]: Unable to parse /home/runner/.ansible.hosts.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'synchronize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/app/datadog-docker.yml': line 94, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    when: postgres_host.stat.exists
  - name: Synchronize datadog/conf.d directory
    ^ here
ansible-playbook 2.11.0.dev0
```

**Comment by albertvaka** [comment]
Thanks for your reply :) I guess that means we need to do what I mentioned in https://github.com/DataDog/ansible-datadog/issues/289#issuecomment-670466471

**Comment by KSerrania** [comment]
Hi @nicon89,

Thanks for the report! To help us troubleshoot your issue, could you give us the contents of the `datadog-docker.yml` configuration file you used (with secrets redacted)?

**Comment by naisanzaa** [comment]
Mac Ansible 2.10.4 **WORKS**
Centos Ansible 2.10.7 **BROKEN**
