### ISSUE TITLE
Dependency issues on debian based deployment

### ISSUE THREAD

**Issue by ebonharme** [DataDog/ansible-datadog#35]
I've noticed that my deployments were failing recently as what is presumably a release containing a security issue was removed from the Ubuntu repositories. https://github.com/DataDog/ansible-datadog/pull/34 should fix.

**Comment by hush-hush** [comment]
Hi @ebonharme, thanks for opening this issue !

Updating the apt cache every hour maybe a little aggressive, especially since network operation are prone to fail.
But the `state=latest` is actually not needed, a simple `state=present` would fix the problem you raised without forcing a cache update.

I will update that today, feel free to add a comment if you have anything to add. Thanks!

**Comment by ebonharme** [comment]
Thanks for attending to this issue @hush-hush. In my specific use case, it's rare that I go and reconfigure agent but good thinking. `state=present` is good. Closing
