### ISSUE TITLE
Playbook should allow dd-agent execution user configuration

### ISSUE THREAD

**Issue by kbreit** [DataDog/ansible-datadog#367]
I want to run the datadog-agent as root but it appears the role doesn't allow customization of which user is configured for execution. I'd expect this modifies the systemd unit file.

**Comment by bkabrda** [comment]
Hi 👋 thanks for opening this issue. This is currently not possible with the role. Can I ask you why you need to run the agent as root? We usually discourage this because of security reasons (the agent should have exactly privileges to do what it needs to do and not more) - maybe there's some other way to achieve what you're trying to achieve?

**Comment by kbreit** [comment]
It was largely for accessing system log files. We certainly could change the groups on the log files but in this particular environment, setting datadog-agent's user was significantly faster. Admittedly, not the right approach. Closing.
