### ISSUE TITLE
Task: Create main Datadog agent configuration file fails with Jinja2 3.1.1

### ISSUE THREAD

**Issue by thelner** [DataDog/ansible-datadog#427]
Task: Create main Datadog agent configuration file task fails when using Jinja2 3.1.1 (released March 25 2022 https://pypi.org/project/Jinja2/3.1.1/)

```
TASK [bootstrap/datadog : Create main Datadog agent configuration file] ********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "TemplateRuntimeError: No filter named 'to_nice_yaml' found."}
```

Task works again after downgrading to Jinja2==3.0.3.
Not sure yet if this is a bug here or in Jinja2 3.1.1.

**Comment by albertvaka** [comment]
Hi @thelner! I looked a bit into this. It seems that `to_nice_yaml` is a filter that Ansible adds to Jinja, so the issue might be due to your particular version of Ansible not being compatible with Jinja 3.1 What Ansible version do you have? If it's a recent enough version, have you checked if this has been reported in Ansible?

**Comment by thelner** [comment]
@albertvaka That is a very good point, I had forgotten that our build server is locked to a very old version of Ansible (2.8.4). I tested Jinja2 3.1.1 with the last of 2.8 line (2.8.20), same result. However latest of 2.9 line (2.9.27) works with Jinja2 3.1.1. Ansible 2.8 is EOL, and has been for a long time. I now realize this is definitely not a bug, it is our legacy problem. Thanks for point in the right direction!
