### ISSUE TITLE
No filter named 'to_nice_yaml' found.

### ISSUE THREAD

**Issue by nduka145** [DataDog/ansible-datadog#480]
Any idea what is causing the following error and how to resolve it. We are running this on;

Ubuntu = 16.04.7
ansible ==2.9.14

TASK [Datadog.datadog : Create main Datadog agent configuration file] **********

fatal: [jenkins0.prod.data.345.com]: FAILED! => {"changed": false, "msg": "TemplateRuntimeError: No filter named 'to_nice_yaml' found."}

**Comment by KSerrania** [comment]
Hi @nduka145,

Thanks for raising this issue. This seems similar to the issues mentioned in https://github.com/ansible/ansible/issues/77413, https://github.com/ansible/ansible/issues/77383.

According to https://github.com/ansible/ansible/issues/77413#issuecomment-1083231487, this type of issues with Jinja filters was fixed in Ansible 2.9.22 (for the Ansible 2.9 line). Could you try upgrading to this version (or a later one) and try again?

**Comment by alopezz** [comment]
Upstream issue fixed as per the last comment.
