### ISSUE TITLE
Issues with Centos 7

### ISSUE THREAD

**Issue by Meraxes** [DataDog/ansible-datadog#71]
Running this role on a Centos 7 instance produces the following error:

IOError: [Errno 13] Permission denied: '/var/log/datadog/supervisord.log'

Tried applying appropriate permissions for the "dd-agent" user but that didn't work. 

Solution for me was to update the user to root under the following config file / section:

file:/etc/dd-agent/supervisor.conf
section: [supervisord]

Anyone else have similar issues?

**Comment by olivielpeau** [comment]
Hi @Meraxes and sorry for my late reply.

This issue doesn't look directly related with the present role, but more with the agent package in general.

As a general rule though we discourage running the Agent as root.

I don't think the issue you ran into is very common, it could be linked to your specific environment. Could you send a [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare) to our support team so that they can help you with your issue?

Thanks!
