### ISSUE TITLE
include has been deprecated

### ISSUE THREAD

**Issue by xkrt** [DataDog/ansible-datadog#78]
Using of `include:` statement is deprecated in Ansible 2.4.0:
```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by olivielpeau** [comment]
Thanks for reporting this @xkrt! Will investigate this for the next minor release of this role 👍

**Comment by olivielpeau** [comment]
Ansible documentation on this: http://docs.ansible.com/ansible/latest/include_module.html

It appears the replacements for `include` (`import_tasks` or `include_tasks`) only exist since ansible `2.4.0`, as such getting rid of the deprecation in this role would make the role incompatible with ansible `< 2.4.0`, which is a breaking change.

`include` will be supported until ansible `2.8.0`, so I don't think we should make this breaking change until `2.8.0` is near.

**Comment by hush-hush** [comment]
Ansible 2.5 seems to have remove the warning on `include`. Like @olivielpeau said, removing include would make the role incompatible with ansible < 2.4.0.

Closing this issue for now and creating a card in our backlog to remove `include` when 2.8.0 is rear (or at leat 2.3 is further away).

**Comment by shyam-habarakada** [comment]
I am looking at 2.9 docs and there is no mention of `include` being deprecated https://docs.ansible.com/ansible/2.9/modules/include_module.html

**Comment by mx-psi** [comment]
@shyam-habarakada If you look at the 'Notes' section in the link you sent you can see the following statement
> This module will still be supported for some time but we are looking at deprecating it in the near future.
